### ISSUE TITLE
More PHP 8.1 deprecation warnings

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/phpexcel#3]
Downloading a table can give this deprecation warning:

> Deprecated function: Implicit conversion from float 65.03846153846153 to int loses precision in PHPExcel_Cell::stringFromColumnIndex() (line 845 of /mysite/modules/contrib/phpexcel/libraries/PHPExcel/Classes/PHPExcel/Cell.php).

To eliminate the warnings, we need explicit casts to `(int)` on lines 845, 848, and 849 (result of the division operation).

PR to come.

**Comment by VasasA** [comment]
@bugfolder Thank You for the two PRs. Please check the Configuration > Development > Testing > PHPExcel
It generates 1 fail and 564 exceptions before PRs merge, and 1 fail and 561 exceptions after merge. Because, as you wrote, [PHPExcel library is no longer being supported](https://github.com/PHPOffice/PHPExcel). Is there anything we can improve on it? Should we also improve the code of the library in this repo?

**Comment by bugfolder** [comment]
Hi @VasasA, I figured there were probably more cases like that; I just fixed the ones that were hitting my site. I'll look into fixing the deprecation warnings in PHPExcel for this module's library, but I think a better long-term solution is probably to create a PHPSpreadsheet module (based on https://github.com/PHPOffice/PhpSpreadsheet, the successor to PHPExcel) for PHP versions 8.0+. Maybe follow the [migration from PHPExcel guide](https://phpspreadsheet.readthedocs.io/en/latest/topics/migration-from-PHPExcel/) to migrate PHPExcel module to the new module (which I would suggest warrants a new module name, `phpspreadsheet`).

**Comment by VasasA** [comment]
👍  It really is a better long-term solution.
Now I'm going to merge the two PRs. I will publish a new release (1.x-3.11.2), but only when you suggest it.
